### ISSUE TITLE
Support Spokfile and spokfile

### ISSUE THREAD

**Issue by gedw99** [FollowTheProcess/spok#178]
just because thats how things are.

makefile and Makefile both work and so we should do the same for spokfile and Spokfile.

easy fix ...

**Comment by FollowTheProcess** [comment]
Yeah this seems reasonable. I think what I'm probably going to do is "freeze" spok (it will obviously still work and I will still patch it etc.) as the more I think about it the more I want to start fresh and build on some lessons in a new thing.

I'm a much better dev than I was when I first wrote this 😂 So there's a lot I'd like to change including some brand new ideas and I think it needs a blank canvas rather than lots of refactoring of an existing thing
